src/Entity/Actu.php
<?php

namespace App\Entity;

use App\Repository\ActuRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use function PHPUnit\Framework\isNull;

#[ORM\Entity(repositoryClass: ActuRepository::class)]
class Actu
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?int $year = null;

    #[ORM\Column(length: 255)]
    private ?string $title = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $text = null;

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $date = null;

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $enddate = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $file = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getYear(): ?int
    {
        return $this->year;
    }

    public function setYear(?int $year): static
    {
        $this->year = $year;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): static
    {
        $this->title = $title;

        return $this;
    }

    public function getText(): ?string
    {
        return $this->text;
    }

    public function setText(?string $text): static
    {
        $this->text = $text;

        return $this;
    }

    public function getDateString() : string
    {
        if ($this->enddate == null) {
            return "Le " . $this->date->format('d') . " " . $this->date->format('M') . " " . $this->date->format('Y');
        } else if ($this->date->format('m') != $this->enddate->format('m')) {
            return "Du " . $this->date->format('d') . " " . $this->date->format('M') . " "
                . " au " . $this->enddate->format('d') . " " . $this->enddate->format('M') . " " . $this->enddate->format('Y');
        } else {
            return "Du " . $this->date->format('d') . " "
                . " au " . $this->enddate->format('d') . " " . $this->enddate->format('M') . " " . $this->enddate->format('Y');
        }
    }

    public function setDate(?\DateTimeInterface $date): static
    {
        $this->date = $date;

        return $this;
    }

    public function setEndDate(?\DateTimeInterface $date): static
    {
        $this->enddate = $date;

        return $this;
    }

    public function getFile(): ?string
    {
        return $this->file;
    }

    public function setFile(?string $file): static
    {
        $this->file = $file;

        return $this;
    }
}

templates/pages/actus.html.twig
{% extends 'components/base.html.twig' %}

{% block title %}Imagin'Woo - Actualités{% endblock %}

{% block dataController %}
    actus
{% endblock %}

{% block body %}
    <section class="page-section container">
        <nav aria-label="Page navigation example" class="">
            <ul class="pagination justify-content-center flex-wrap">
                {% if year+1 in years %}
                    <li class="page-item h-auto d-flex align-items-stretch"><a class="page-link d-flex align-items-center" href="{{ path('app_actus', {'year': years[0]}) }}"><i class="bi bi-chevron-double-left"></i></a></li>
                    <li class="page-item h-auto d-none d-md-flex align-items-stretch"><a class="page-link d-flex align-items-center" href="{{ path('app_actus', {'year': year+1}) }}"><i class="bi bi-chevron-left ms-1"></i> Page précédente</a></li>
                    {% if year+3 in years %}
                        <li class="page-item h-auto d-flex align-items-stretch"><a class="page-link d-flex align-items-center disabled"> ... </a></li>
                    {% endif %}
                    {% if year+2 in years %}
                        <li class="page-item h-auto d-flex align-items-stretch"><a class="page-link d-flex align-items-center" href="{{ path('app_actus', {'year': year+2}) }}">{{ year+2 }}</a></li>
                    {% endif %}
                    <li class="page-item h-auto d-flex align-items-stretch"><a class="page-link d-flex align-items-center" href="{{ path('app_actus', {'year': year+1}) }}">{{ year+1 }}</a></li>
                {% endif %}
                <li class="page-item h-auto d-flex align-items-stretch"><a class="page-link d-flex align-items-center active" href="{{ path('app_actus', {'year': year}) }}">{{ year }}</a></li>
                {% if year-1 in years %}
                    <li class="page-item h-auto d-flex align-items-stretch"><a class="page-link d-flex align-items-center" href="{{ path('app_actus', {'year': year-1}) }}">{{ year-1 }}</i></a></li>
                    {% if year-2 in years %}
                        <li class="page-item h-auto d-flex align-items-stretch"><a class="page-link d-flex align-items-center" href="{{ path('app_actus', {'year': year-2}) }}">{{ year-2 }}</i></a></li>
                    {% endif %}
                    {% if year-3 in years %}
                        <li class="page-item h-auto d-flex align-items-stretch"><a class="page-link d-flex align-items-center disabled"> ... </a></li>
                    {% endif %}
                    <li class="page-item h-auto d-none d-md-flex align-items-stretch"><a class="page-link d-flex align-items-center" href="{{ path('app_actus', {'year': year-1}) }}">Page suivante <i class="bi bi-chevron-right me-1"></i></a></li>
                    <li class="page-item h-auto d-flex align-items-stretch"><a class="page-link d-flex align-items-center" href="{{ path('app_actus', {'year': years[years|length-1]}) }}"><i class="bi bi-chevron-double-right"></i></a></li>
                {% endif %}
            </ul>
        </nav>
    </section>
    <section id="cardDiv" class="page-section">
        {% for actu in actus %}
            <div class="container d-flex flex-row flex-wrap justify-content-between">
                <div class="card mb-3 w-100">
                    <div class="row g-0">
                        <div class="col-md-4">
                            <img src="{{ asset('img/actus/' ~ actu.file ~ '') }}" class="img-fluid card-img-fill rounded-start"
                                 alt="...">
                        </div>
                        <div class="col-md-8">
                            <div class="card-body text-start h-100 d-flex flex-column p-5">
                                <div>
                                <h5 class="card-title">{{ actu.title }}</h5>
                                    <p class="card-text">
                                        <small class="text-body-secondary fst-italic">
                                            {{ actu.dateString }}
                                        </small>
                                    </p>
                                </div>
                                <p class="card-text my-auto ">
                                    {{ actu.text|raw }}
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </section>
{% endblock %}

templates/pages/agenda.html.twig
{% extends 'components/base.html.twig' %}

{% block title %}Imagin'Woo - Agenda{% endblock %}

{% block body %}
    <section class="page-section container">
        <div class="about-heading-content mb-4">
            <div class="row">
                <div class="col-xl-9 col-lg-10 mx-auto">
                    <div class="bg-faded rounded p-5">
                        <h2 class="section-heading mb-4">
                            <span class="section-heading-lower">Agenda</span>
                        </h2>
                        <p class="mb-0">
                            Découvrez le planning du club, les dates des prochaines sorties et réunions planifiées.
                        </p>
                    </div>
                </div>
            </div>
        </div>
        <iframe src="https://embed.styledcalendar.com/#mt77g2u3fBluZC4uVKoW" title="Styled Calendar"
                class="styled-calendar-container" style="width: 100%; border: none;"
                data-cy="calendar-embed-iframe"></iframe>
        <script async type="module" src="https://embed.styledcalendar.com/assets/parent-window.js"></script>
    </section>
{% endblock %}

templates/pages/contact.html.twig
{% extends 'components/base.html.twig' %}

{% block title %}Imagin'Woo - Contact{% endblock %}

{% block dataController %}
    contact
{% endblock %}

{% block body %}
    <section class="page-section container">
        <div class="bg-faded rounded m-4 p-4">
            <div class="py-5 text-center">
                <h2>Nous contacter</h2>
                <p class="lead">Afin de nous contacter, veuillez remplir le formulaire suivant, nous nous efforcerons de
                    vous répondre au plus vite.</p>
            </div>

            <div class="col-md-7 col-lg-8 mx-auto">
                <h4 class="mb-3">Vos informations</h4>
                {{ form(form) }}
            </div>
        </div>
    </section>
{% endblock %}

templates/pages/index.html.twig
{% extends 'components/base.html.twig' %}

{% block body %}
    <section class="page-section clearfix" style="margin-bottom: 8rem !important;">
        <div class="container">
            <div class="intro">
                <img class="intro-img img-fluid mb-3 mb-lg-0 rounded" src="{{ asset('img/intro.jpg') }}" alt="..."/>
                <div class="intro-text left-0 text-center bg-faded p-5 rounded">
                    <h2 class="section-heading mb-4">
                        <span class="section-heading-upper">Bienvenue sur le site du </span>
                        <span class="section-heading-lower">club photo de Waterloo</span>
                    </h2>
                    <p class="mb-3">L’objectif de ce club est de favoriser les rencontres entre photographes amateurs ou
                        professionnels. Le seul impératif pour nous rejoindre est de posséder un appareil
                        photographique. Que ce soit l'argentique ou le numérique, ce qui nous rassemble, c'est notre
                        passion commune de la photographie !</p>
                    <div class="intro-button mx-auto"><a class="btn btn-primary btn-xl" href="/contact">Nous
                            rejoindre!</a></div>
                </div>
            </div>
        </div>
    </section>
    <section class="page-section cta">
        <div class="container">
            <div class="row">
                <div class="col-xl-9 mx-auto">
                    <div class="cta-inner bg-faded text-center rounded">
                        <h2 class="section-heading mb-4">
                            <span class="section-heading-lower">Le club</span>
                        </h2>
                        <p class="mb-0">
                            l'A.S.B.L. Imagin'Woo club photo Waterloo a vu le jour au mois d'octobre 2015 à l'initiative de Valérie, photographe waterlootoise.
                            <br>
                            Chaque mois une sortie photo est programmée ainsi qu'une réunion au cours de laquelle nous visionnons nos images et organisons les sorties et évènements à venir (voir dans l’onglet agenda).
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <section class="page-section container">
        <div class="product-item">
            <div class="product-item-title d-flex">
                <div class="bg-faded p-4 d-flex flex-column me-auto rounded w-50-flex">
                    <h2 class="section-heading mb-0">
                        <span class="text-primary fs-5 fw-bold">Exposition 2023 Le coup de cœur du public</span>
                    </h2>
                    <p class="mb-0 mt-2" style="line-height: 1.2rem;">Comme chaque année, les visiteurs de l'exposition
                        ont voté pour élire leur coup de cœur... Voici le top 10 de cette édition 2023</p>
                </div>
            </div>
            <div id="carouselClassementExpo" class="carousel slide" data-bs-ride="carousel" data-bs-interval="3500">
                <div class="carousel-indicators">
                    <button type="button" data-bs-target="#carouselClassementExpo" data-bs-slide-to="0" class="active"
                            aria-current="true" aria-label="Slide 1"></button>
                    <button type="button" data-bs-target="#carouselClassementExpo" data-bs-slide-to="1"
                            aria-label="Slide 2"></button>
                    <button type="button" data-bs-target="#carouselClassementExpo" data-bs-slide-to="2"
                            aria-label="Slide 3"></button>
                    <button type="button" data-bs-target="#carouselClassementExpo" data-bs-slide-to="3"
                            aria-label="Slide 4"></button>
                    <button type="button" data-bs-target="#carouselClassementExpo" data-bs-slide-to="4"
                            aria-label="Slide 4"></button>
                    <button type="button" data-bs-target="#carouselClassementExpo" data-bs-slide-to="5"
                            aria-label="Slide 5"></button>
                    <button type="button" data-bs-target="#carouselClassementExpo" data-bs-slide-to="6"
                            aria-label="Slide 6"></button>
                    <button type="button" data-bs-target="#carouselClassementExpo" data-bs-slide-to="7"
                            aria-label="Slide 7"></button>
                    <button type="button" data-bs-target="#carouselClassementExpo" data-bs-slide-to="8"
                            aria-label="Slide 8"></button>
                    <button type="button" data-bs-target="#carouselClassementExpo" data-bs-slide-to="9"
                            aria-label="Slide 9"></button>
                </div>
                <div class="carousel-inner">
                    <div class="carousel-item active">
                        <img src="{{ asset('img/coupsdecoeurs/01 - SANGUINETTI VALERIE.jpg') }}" class="d-block w-100"
                             alt="...">
                        <div class="carousel-caption d-none d-md-block">
                            <h5>1 - Valérie Sanguinetti</h5>
                            <p>540 Votes</p>
                        </div>
                    </div>
                    <div class="carousel-item">
                        <img src="{{ asset('img/coupsdecoeurs/02 - LAMBERT CARINE.jpg') }}" class="d-block w-100"
                             alt="...">
                        <div class="carousel-caption d-none d-md-block">
                            <h5>2 - Carine lambert</h5>
                            <p>520 Votes</p>
                        </div>
                    </div>
                    <div class="carousel-item">
                        <img src="{{ asset('img/coupsdecoeurs/03 - KENTOS ALAIN.jpg') }}" class="d-block w-100"
                             alt="...">
                        <div class="carousel-caption d-none d-md-block">
                            <h5>3 - Alain Kentos</h5>
                            <p>473 Votes</p>
                        </div>
                    </div>
                    <div class="carousel-item">
                        <img src="{{ asset('img/coupsdecoeurs/04 - GILLES CARINE.jpg') }}" class="d-block w-100"
                             alt="...">
                        <div class="carousel-caption d-none d-md-block">
                            <h5>4 - Carine Gilles</h5>
                            <p>450 Votes</p>
                        </div>
                    </div>
                    <div class="carousel-item">
                        <img src="{{ asset('img/coupsdecoeurs/05 - KEBERS MARIE CLAUDE.jpg') }}" class="d-block w-100"
                             alt="...">
                        <div class="carousel-caption d-none d-md-block">
                            <h5>5 - Marie-Claude Kebers</h5>
                            <p>432 Votes</p>
                        </div>
                    </div>
                    <div class="carousel-item">
                        <img src="{{ asset('img/coupsdecoeurs/06 - JOET ANNE.jpg') }}" class="d-block w-100" alt="...">
                        <div class="carousel-caption d-none d-md-block">
                            <h5>6 - Anne Joet</h5>
                            <p>424 Votes</p>
                        </div>
                    </div>
                    <div class="carousel-item">
                        <img src="{{ asset('img/coupsdecoeurs/07 - GALLET MICHELE.jpg') }}" class="d-block w-100 img-hr"
                             alt="">
                        <div class="carousel-caption d-none d-md-block">
                            <h5>7 - Michèle Gallet</h5>
                            <p>419 Votes</p>
                        </div>
                    </div>
                    <div class="carousel-item">
                        <img src="{{ asset('img/coupsdecoeurs/08 - LAMBERT CARINE.jpg') }}" class="d-block w-100"
                             alt="...">
                        <div class="carousel-caption d-none d-md-block">
                            <h5>8 - Carine Lambert</h5>
                            <p>417 Votes</p>
                        </div>
                    </div>
                    <div class="carousel-item">
                        <img src="{{ asset('img/coupsdecoeurs/09 - VANDERWAEREN MICHEL.jpg') }}" class="d-block w-100"
                             alt="...">
                        <div class="carousel-caption d-none d-md-block">
                            <h5>9 - Michel Vanderwaeren</h5>
                            <p>397 Votes</p>
                        </div>
                    </div>
                    <div class="carousel-item">
                        <img src="{{ asset('img/coupsdecoeurs/10 - RIXHON MARIANNE.jpg') }}" class="d-block w-100"
                             alt="...">
                        <div class="carousel-caption d-none d-md-block">
                            <h5>10 - Marianne Rixhon</h5>
                            <p>396 Votes</p>
                        </div>
                    </div>
                </div>
                <button class="carousel-control-prev" type="button" data-bs-target="#carouselClassementExpo"
                        data-bs-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Previous</span>
                </button>
                <button class="carousel-control-next" type="button" data-bs-target="#carouselClassementExpo"
                        data-bs-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Next</span>
                </button>
            </div>
        </div>
    </section>
{% endblock %}

templates/pages/presse.html.twig
{% extends 'components/base.html.twig' %}

{% block title %}Imagin'Woo - Galerie des membres{% endblock %}

{% block stylesheets %}
    <link rel="stylesheet" href="{{ asset('styles/galery.css') }}">
{% endblock %}

{% block dataController %}
    galery
{% endblock %}

{% block body %}
    <section class="page-section container">
        <div class="about-heading-content mb-4">
            <div class="row">
                <div class="col-xl-9 col-lg-10 mx-auto">
                    <div class="bg-faded rounded p-5">
                        <h2 class="h2">
                            <span class="section-heading-lower">On parle de nous ...</span>
                        </h2>
                    </div>
                </div>
            </div>
        </div>

        <div class="progress m-4 mt-5" role="progressbar" aria-label="Animated striped example" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100">
            <div id="progress-bar" class="progress-bar progress-bar-striped progress-bar-animated" style="width: 1%">Chargement... 1%</div>
        </div>

        <article class='gallery d-none'>
            <a class='gallery-link' href='{{ asset('img/presse/2016 dec Image Mag.jpg') }}'>
                <figure class='gallery-image'>
                    <img class='gallery-img' height='1400' src='{{ asset('img/presse/2016 dec Image Mag.jpg') }}' width='1000' alt="">
                    <figcaption>2016 dec Image Mag</figcaption>
                </figure>
            </a>
            <a class='gallery-link' href='{{ asset('img/presse/2020 Oct Waterloo info.JPG') }}'>
                <figure class='gallery-image'>
                    <img class='gallery-img' height='1400' src='{{ asset('img/presse/2020 Oct Waterloo info.JPG') }}' width='1000' alt="">
                    <figcaption>2020 Oct Waterloo info</figcaption>
                </figure>
            </a>
            <a class='gallery-link' href='{{ asset('img/presse/juin 2021  Waterloo info.JPG') }}'>
                <figure class='gallery-image'>
                    <img class='gallery-img' height='1400' src='{{ asset('img/presse/juin 2021  Waterloo info.JPG') }}' width='1000' alt="">
                    <figcaption>juin 2021  Waterloo info</figcaption>
                </figure>
            </a>
            <a class='gallery-link' href='{{ asset('img/presse/Nov 2022 Waterloo info 1665.jpg') }}'>
                <figure class='gallery-image'>
                    <img class='gallery-img' height='1400' src='{{ asset('img/presse/Nov 2022 Waterloo info 1665.jpg') }}' width='1000' alt="">
                    <figcaption>Nov 2022 Waterloo info 1665</figcaption>
                </figure>
            </a>
            <a class='gallery-link' href='{{ asset('img/presse/Oct 2017 Waterloo info.jpg') }}'>
                <figure class='gallery-image'>
                    <img class='gallery-img' height='1400' src='{{ asset('img/presse/Oct 2017 Waterloo info.jpg') }}' width='1000' alt="">
                    <figcaption>Oct 2017 Waterloo info</figcaption>
                </figure>
            </a>
            <a class='gallery-link' href='{{ asset('img/presse/Oct 2018 Images Mag oct. 2018.jpg') }}'>
                <figure class='gallery-image'>
                    <img class='gallery-img' height='1400' src='{{ asset('img/presse/Oct 2018 Images Mag oct. 2018.jpg') }}' width='1000' alt="">
                    <figcaption>Oct 2018 Images Mag oct. 2018</figcaption>
                </figure>
            </a>
            <a class='gallery-link' href='{{ asset('img/presse/Oct 2019 Waterloo info.JPG') }}'>
                <figure class='gallery-image'>
                    <img class='gallery-img' height='1400' src='{{ asset('img/presse/Oct 2019 Waterloo info.JPG') }}' width='1000' alt="">
                    <figcaption>Oct 2019 Waterloo info</figcaption>
                </figure>
            </a>
            <a class='gallery-link' href='{{ asset('img/presse/Oct 2021 Waterloo info.JPG') }}'>
                <figure class='gallery-image'>
                    <img class='gallery-img' height='1400' src='{{ asset('img/presse/Oct 2021 Waterloo info.JPG') }}' width='1000' alt="">
                    <figcaption>Oct 2021 Waterloo info</figcaption>
                </figure>
            </a>
            <a class='gallery-link' href='{{ asset('img/presse/Oct 2023 Waterloo info n°1700.jpg') }}'>
                <figure class='gallery-image'>
                    <img class='gallery-img' height='1400' src='{{ asset('img/presse/Oct 2023 Waterloo info n°1700.jpg') }}' width='1000' alt="">
                    <figcaption>Oct 2023 Waterloo info n°1700</figcaption>
                </figure>
            </a>
            <a class='gallery-link' href='{{ asset('img/presse/sept 2016 BW.jpg') }}'>
                <figure class='gallery-image'>
                    <img class='gallery-img' height='1400' src='{{ asset('img/presse/sept 2016 BW.jpg') }}' width='1000' alt="">
                    <figcaption>sept 2016 BW</figcaption>
                </figure>
            </a>
            <a class='gallery-link' href='{{ asset('img/presse/sept 2018 Woo info.JPG') }}'>
                <figure class='gallery-image'>
                    <img class='gallery-img' height='1400' src='{{ asset('img/presse/sept 2018 Woo info.JPG') }}' width='1000' alt="">
                    <figcaption>sept 2018 Woo info</figcaption>
                </figure>
            </a>
            <a class='gallery-link' href='{{ asset('img/presse/sept 2016 Waterloo-info.jpg') }}'>
                <figure class='gallery-image'>
                    <img class='gallery-img' height='1400' src='{{ asset('img/presse/sept 2016 Waterloo-info.jpg') }}' width='1000' alt="">
                    <figcaption>sept 2016 Waterloo-info</figcaption>
                </figure>
            </a>
            <a class='gallery-link' href='{{ asset('img/presse/sept 2018 annonce brabanconne.jpg') }}'>
                <figure class='gallery-image'>
                    <img class='gallery-img' height='1400' src='{{ asset('img/presse/sept 2018 annonce brabanconne.jpg') }}' width='1000' alt="">
                    <figcaption>sept 2018 annonce brabanconne.jpg</figcaption>
                </figure>
            </a>
        </article>
    </section>
{% endblock %}